return {}
-- return {
--   {
--     "supermaven-inc/supermaven-nvim",
--     opts = {
--       disable_inline_completion = true, -- disables inline completion for use with cmp
--       disable_keymaps = true, -- disables built in keymaps for more manual control
--     },
--   },
--   {
--     "hrsh7th/nvim-cmp",
--     dependencies = { "supermaven-inc/supermaven-nvim" },
--     opts = function(_, opts)
--       table.insert(opts.sources, 1, {
--         name = "supermaven",
--         group_index = 1,
--         priority = 100,
--       })
--     end,
--   },
-- }
