return {
  "mistweaverco/kulala.nvim",
  ft = "http",
  keys = {
    { "<localleader>", "", desc = "+Rest", ft = "http" },
    { "<localleader>b", "<cmd>lua require('kulala').scratchpad()<cr>", desc = "Open scratchpad", ft = "http" },
    { "<localleader>c", "<cmd>lua require('kulala').copy()<cr>", desc = "Copy as cURL", ft = "http" },
    { "<localleader>C", "<cmd>lua require('kulala').from_curl()<cr>", desc = "Paste from curl", ft = "http" },
    {
      "<localleader>g",
      "<cmd>lua require('kulala').download_graphql_schema()<cr>",
      desc = "Download GraphQL schema",
      ft = "http",
    },
    { "<localleader>i", "<cmd>lua require('kulala').inspect()<cr>", desc = "Inspect current request", ft = "http" },
    { "<localleader>n", "<cmd>lua require('kulala').jump_next()<cr>", desc = "Jump to next request", ft = "http" },
    {
      "<localleader>p",
      "<cmd>lua require('kulala').jump_prev()<cr>",
      desc = "Jump to previous request",
      ft = "http",
    },
    { "<localleader>q", "<cmd>lua require('kulala').close()<cr>", desc = "Close window", ft = "http" },
    { "<localleader>r", "<cmd>lua require('kulala').replay()<cr>", desc = "Replay the last request", ft = "http" },
    { "<localleader>s", "<cmd>lua require('kulala').run()<cr>", desc = "Send the request", ft = "http" },
    { "<localleader>S", "<cmd>lua require('kulala').show_stats()<cr>", desc = "Show stats", ft = "http" },
    { "<localleader>t", "<cmd>lua require('kulala').toggle_view()<cr>", desc = "Toggle headers/body", ft = "http" },
  },
  opts = {},
}
