;; extends
;; Keywords
(("import"   @keyword) (#set! conceal  "󰋺"))
(("package"  @keyword) (#set! conceal  ""))
(("func"     @keyword) (#set! conceal "󰊕"))
(("for"      @keyword) (#set! conceal ""))
(("type"  @keyword) (#set! conceal  ""))
(("const"   @keyword) (#set! conceal ""))
(("var"   @keyword) (#set! conceal ""))
(("return"   @keyword) (#set! conceal ""))
(("struct"   @keyword) (#set! conceal ""))
(("interface"   @keyword) (#set! conceal ""))
(("go"   @keyword) (#set! conceal "󰟓"))
(("if"      @keyword) (#set! conceal ""))
(("else"      @keyword) (#set! conceal "󰅱"))
(("switch"      @keyword) (#set! conceal ""))
(("case"      @keyword) (#set! conceal ""))
; (("range"      @keyword) (#set! conceal  ""))
